export const DASHBOARD_SCREEN = "DASHBOARD_SCREEN";
export const GAME_SCREEN = "GAMESCREEN";

export const CREATE_GAME_REQUEST = "CREATE_GAME_REQUEST";
export const CREATE_GAME_SUCCESS = "CREATE_GAME_SUCCESS";
export const CREATE_GAME_FAILURE = "CREATE_GAME_FAILURE";

export const JOIN_GAME_REQUEST = "JOIN_GAME_REQUEST";
export const JOIN_GAME_SUCCESS = "JOIN_GAME_SUCCESS";
export const JOIN_GAME_FAILURE = "JOIN _GAME_FAILURE";

export const SELECT_CARD_REQUEST = "SELECT_CARD_REQUEST";
export const SELECT_CARD_SUCCESS = "SELECT_CARD_SUCCESS";
export const SELECT_CARD_FAILIURE = "SELECT_CARD_FAILURE";
