export const CHANGE_SCREEN = "CHANGE_SCREEN";

export const OPEN_JOIN_GAME_MODAL = "OPEN_JOIN_GAME_MODAL";
export const CLOSE_JOIN_GAME_MODAL = "CLOSE_JOIN_GAME_MODAL";
export const OPEN_CREATE_GAME_MODAL = "OPEN_CREATE_GAME_MODAL";
export const CLOSE_CREATE_GAME_MODAL = "CLOSE_CREATE_GAME_MODAL";

export const CREATE_GAME = "CREATE_GAME";
export const DELETE_GAME = "DELETE_GAME";

export const SET_SELECTED_GAME = "SET_SELECTED_GAME";

export const SET_PLAYER_NAME = "SET_PLAYER_NAME";

export const CREATE_GAME_REQUEST = "CREATE_GAME_REQUEST";
export const CREATE_GAME_SUCCESS = "CREATE_GAME_SUCCESS";
export const CREATE_GAME_FAILURE = "CREATE_GAME_FAILURE";

export const JOIN_GAME_REQUEST = "JOIN_GAME_REQUEST";
export const JOIN_GAME_SUCCESS = "JOIN_GAME_SUCCESS";
export const JOIN_GAME_FAILURE = "JOIN _GAME_FAILURE";

export const SELECT_CARD_REQUEST = "SELECT_CARD_REQUEST";
export const SELECT_CARD_SUCCESS = "SELECT_CARD_SUCCESS";
export const SELECT_CARD_FAILIURE = "SELECT_CARD_FAILURE";

export const SELECT_SPY_MASTER = "SELECT_SPY_MASTER";
